/* Generated By:JavaCC: Do not edit this line. ConditionParserConstants.java */
package com.zliao.chacha.service.RuleEngine.transitioncondition;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ConditionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int NOT = 7;
  /** RegularExpression Id. */
  int LPAREN = 8;
  /** RegularExpression Id. */
  int RPAREN = 9;
  /** RegularExpression Id. */
  int TRUE = 10;
  /** RegularExpression Id. */
  int FALSE = 11;
  /** RegularExpression Id. */
  int EQUALS = 12;
  /** RegularExpression Id. */
  int NOTEQUAL = 13;
  /** RegularExpression Id. */
  int STARTSWITH = 14;
  /** RegularExpression Id. */
  int ENDSWITH = 15;
  /** RegularExpression Id. */
  int CONTAINS = 16;
  /** RegularExpression Id. */
  int LIKE = 17;
  /** RegularExpression Id. */
  int REGEX = 18;
  /** RegularExpression Id. */
  int IDENTIFIER = 19;
  /** RegularExpression Id. */
  int QUOTED_STRING = 20;
  /** RegularExpression Id. */
  int QUOTED_STRING2 = 21;
  /** RegularExpression Id. */
  int DOUBLE = 22;
  /** RegularExpression Id. */
  int INTEGER = 23;
  /** RegularExpression Id. */
  int DBL = 24;
  /** RegularExpression Id. */
  int DIGIT = 25;
  /** RegularExpression Id. */
  int CLASSNAME = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<AND>",
    "<OR>",
    "<NOT>",
    "\"(\"",
    "\")\"",
    "\"true\"",
    "\"false\"",
    "\"=\"",
    "<NOTEQUAL>",
    "\"^=\"",
    "\"$=\"",
    "\"*=\"",
    "\"%=\"",
    "\"~=\"",
    "<IDENTIFIER>",
    "<QUOTED_STRING>",
    "<QUOTED_STRING2>",
    "<DOUBLE>",
    "<INTEGER>",
    "<DBL>",
    "<DIGIT>",
    "<CLASSNAME>",
  };

}
